---
# ESXi hosts booted with the Cisco Custom ISO for ESXi 7.0U3 need
# to have drivers either updated or installed.

#  - name: Download nenic driver to tmp directory
#    command: wget {{ nenic_offline_bundle_url }} -P /tmp
#    args:
#      warn: false

#  - name: Update nenic driver
#    command: esxcli software component apply -d /tmp/{{ nenic_filename }} 
#    args:
#      warn: false

#  - name: Download nenic-ens driver to tmp directory
#    command: wget {{ nenic_ens_offline_bundle_url }} -P /tmp
#    args:
#      warn: false

#  - name: Update nenic-ens driver
#    command: esxcli software component apply -d /tmp/{{ nenic_ens_filename }}
#    args:
#      warn: false

  - name: Download nfnic driver to tmp directory
    command: wget {{ nfnic_offline_bundle_url }} -P /tmp
    args:
      warn: false

  - name: Update nfnic driver
    command: esxcli software component apply -d /tmp/{{ nfnic_filename }}
    args:
      warn: false

  - name: Download lsi-mr3 driver to tmp directory
    command: wget {{ lsi_mr3_offline_bundle_url }} -P /tmp
    args:
      warn: false

  - name: Update lsi-mr3 driver
    command: esxcli software component apply -d /tmp/{{ lsi_mr3_filename }}
    args:
      warn: false

  - name: Download NetApp NFS VAAI Plugin driver to tmp directory
    command: wget {{ NetAppVAAI_offline_bundle_url }} -P /tmp
    args:
      warn: false

  - name: Install NetApp NFS VAAI Plugin driver
    command: esxcli software component apply -d /tmp/{{ NetAppVAAI_filename }}
    args:
      warn: false

#  - name: Download UCS Tools driver to tmp directory
#    command: wget {{ UCS_Tools_url }} -P /tmp
#    args:
#      warn: false

#  - name: Update UCS Tools driver
#    command: esxcli software component apply -d /tmp/{{ UCS_Tools_filename }}
#    args:
#      warn: false

  - name: Enable NVMe with ANA
    command: esxcfg-advcfg -s 0 /Misc/HppManageDegradedPaths
    args:
      warn: false

  - name: Reboot Host
    command: reboot
    args:
      warn: false
